name: Build

on:
  push:
    branches:
    - specs
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      CI: true
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.0"]
        gemfile: ["gemfiles/rails6.gemfile"]
        include:
        - ruby: "2.6"
          gemfile: "gemfiles/rails5.gemfile"
        - ruby: "2.7"
          gemfile: "gemfiles/rails6.gemfile"
        - ruby: "3.0"
          gemfile: "gemfiles/railsmaster.gemfile"
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: bundle-${{ matrix.ruby }}-${{ matrix.gemfile }}-${{ hashFiles(matrix.gemfile) }}-${{ hashFiles('**/*.gemspec') }}
        restore-keys: |
          bundle-${{ matrix.ruby }}-${{ matrix.gemfile }}-
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Bundle install
      run: |
        bundle config path vendor/bundle
        bundle config --global gemfile ${{ matrix.gemfile }}
        bundle install
        bundle update
    - name: Run RSpec
      run: |
        bundle exec rspec

